source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.5.1'

# framework
gem 'kimurai', git: "https://github.com/vfreefly/kimurai"

# require files in directory and child directories recursively
gem 'require_all'

# dotenv
gem 'dotenv'

# For stats database you can use sqlite, postgres or mysql. Uncomment
# prefered gem and run bundle install before provide stats_database_url in config/application.rb
# gem 'sqlite3'
# gem 'pg'
# gem 'mysql2'

group :development do
  gem 'byebug'
  gem 'pry'
end

